title: "Nick Alexander"
url: "https://nickalexander.org"
baseurl: ""
permalink: /:title.html
exclude: ["_word/posts", "_word/drafts", "convert.py", "README.md"]
plugins:
  - jekyll-sitemap

collections:
  ideas:
    output: true
    permalink: /drafts/:title.html
